# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 8, 9, 10, 868000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 8, 9, 10, 866000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 22, 8, 9, 10, 866000, tzinfo=utc)),
        ),
    ]
