# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20181022_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='approved',
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 10, 52, 27, 813000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 10, 52, 27, 811000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
