# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20181022_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 18, 39, 184000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 18, 39, 182000, tzinfo=utc)),
        ),
    ]
