# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20181022_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 12, 32, 54, 668000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 12, 32, 54, 666000, tzinfo=utc)),
        ),
    ]
